mode: deployment
config:
  exporters:
    otlphttp:
      endpoint: http://jaeger-collector.jaeger:4318
  receivers:
    otlp:
      protocols:
        http:
          include_metadata: true
          cors:
            allowed_origins:
              - http://localhost
              - http://localhost:8080
            # allowed_headers:
            #   - Example-Header
            max_age: 7200
  service:
    pipelines:
      traces:
        receivers: [otlp]
        processors: [batch]
        exporters: [otlphttp]