server:
  persistentVolume:
    enabled: false
  retention: "1d"
  extraArgs: 
    enable-feature: remote-write-receiver
  global:
    ## How frequently to scrape targets by default
    ##
    scrape_interval: 10s
    ## How long until a scrape request times out
    ##
    scrape_timeout: 10s
    ## How frequently to evaluate rules
    ##
    evaluation_interval: 10s
  # scrape_configs:
  #   - job_name: 'pods-with-daprd'
  #     kubernetes_sd_configs:
  #     - role: pod
  #     relabel_configs:
  #     - source_labels: [__meta_kubernetes_pod_annotation_dapr_io_app_port]
  #       action: keep
  #     - source_labels: [__address__, __meta_kubernetes_pod_annotation_dapr_io_app_port]
  #       regex: ([^:]+)(?::\d+)?;(\d+)
  #       replacement: $1:$2
  #       target_label: __address__
  #     - action: labelmap
  #       regex: __meta_kubernetes_pod_label_(.+)
  #     - source_labels: [__meta_kubernetes_pod_name]
  #       target_label: pod
  #     - source_labels: [__meta_kubernetes_namespace]
  #       target_label: namespace
alertmanager:
  enabled: false
prometheus-node-exporter:
  enabled: false
prometheus-pushgateway:
  enabled: false
networkPolicy:
  enabled: true