apiVersion: v1
kind: Service
metadata:
  name: jaeger-nodeport
  namespace: jaeger
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger
  ports:
    - name: jaeger
      port: 16686
      targetPort: 16686
      nodePort: 30001 
    # - name: zipkin
    #   port: 9411
    #   targetPort: 9411
    #   nodePort: 30002
    # - name: otel
    #   port: 4318
    #   targetPort: 4318
    #   nodePort: 30002