apiVersion: v1
kind: Service
metadata:
  name: otel-nodeport
  namespace: opentelemetry
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: opentelemetry-collector
  ports:
    - name: otel
      port: 4318
      targetPort: 4318
      nodePort: 30002