apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry
spec:
  config: |
    exporters:
      otlphttp:
        endpoint: http://jaeger-collector.jaeger:4318
    processors:
      transform:
        trace_statements:
          - context: span
            statements:
              - set(attributes["from_shared"], "true")
    receivers:
      otlp:
        protocols:
          http:
            include_metadata: true
            cors:
              allowed_origins:
                - http://localhost
                - http://localhost:8080
              # allowed_headers:
              #   - Example-Header
              max_age: 7200
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [transform]
          exporters: [otlphttp]