apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: sidecar
spec:
  mode: sidecar
  config: |
    receivers:
      otlp:
        protocols:
          http:
          grpc:

    processors:
      transform:
        trace_statements:
          - context: span
            statements:
              - set(attributes["from_sidecar"], "true")

    exporters:
      otlphttp:
        endpoint: http://opentelemetry-collector.opentelemetry:4318

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [transform]
          exporters: [otlphttp]