apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: todos
spec:
  type: state.redis
  version: v1
  metadata: 
  - name: redisHost
    value: redis-master.redis:6379
  - name: redisPassword
    value: notsecure