{
 "title": "App Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(http_requests_received_total, service_name)"
    }
   },
   {
    "name": "endpoint",
    "label": "endpoint",
    "query": {
     "query": "label_values(http_requests_received_total{service_name =~ \"$app\"}, endpoint)"
    }
   },
   {
    "name": "appName",
    "query": {
     "query": "label_values(http_requests_received_total{service_name =~ \"$app\"}, app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests received by endpoint",
   "type": "timeseries",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(http_requests_received_total{service_name =~ \"$app\", endpoint  =~ \"$endpoint\"}[$__rate_interval])) by (endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total req/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(irate(http_requests_received_total{service_name =~ \"$app\", endpoint =~ \"$endpoint\"}[$__rate_interval])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(dotnet_total_memory_bytes{service_name=\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Working Set",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(process_working_set_bytes{service_name=\"$app\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Web API Logs",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{app=\"$app\", container!=\"daprd\"} |= ``"
    }
   ]
  }
 ]
}