{
 "title": "Otel Collector Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Received Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "irate(otelcol_receiver_accepted_spans[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Spans",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(otelcol_exporter_sent_spans[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tail Sampling Outcomes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(policy, sampled) (irate(otelcol_processor_tail_sampling_count_traces_sampled[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}