{
 "title": "Topline Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "app", "query": { "query": "label_values(service_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Global Success Rate",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(irate(microsoft_aspnetcore_hosting_total_requests[$__rate_interval])) \n    -\n    sum(irate(microsoft_aspnetcore_hosting_failed_requests[$__rate_interval])) \n)\n/\n(\n    sum(irate(microsoft_aspnetcore_hosting_total_requests[$__rate_interval])) \n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Global Request Volume",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(microsoft_aspnetcore_hosting_total_requests[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces Monitored",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(microsoft_aspnetcore_hosting_total_requests) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apps Monitored",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(microsoft_aspnetcore_hosting_total_requests) by (namespace, service_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Top Line</span>\n</div>"
   }
  },
  {
   "title": "ASP.NET Core Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "(\n    sum(irate(microsoft_aspnetcore_hosting_total_requests[$__rate_interval])) by (service_name)\n    -\n    sum(irate(microsoft_aspnetcore_hosting_failed_requests[$__rate_interval])) by (service_name)\n)\n/\n(\n    sum(irate(microsoft_aspnetcore_hosting_total_requests[$__rate_interval])) by (service_name)\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASP.NET Core Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "sum(irate(microsoft_aspnetcore_hosting_failed_requests[$__rate_interval])) by (service_name)\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(dapr_http_server_latency_sum[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 14 },
   "options": {
    "content": "<div class=\"text-center dashboard-header\">\n  <span>Applications</span>\n</div>"
   }
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }, "repeat": "app" },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 17 },
   "options": {
    "content": "<div>\n  <span style=\"font-size: 15px; border-image:none\">$app</span>\n</div>"
   }
  },
  {
   "title": "ASP.NET Core Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "(\n    sum(irate(microsoft_aspnetcore_hosting_total_requests{service_name=\"$app\"}[$__rate_interval])) \n    -\n    sum(irate(microsoft_aspnetcore_hosting_failed_requests{service_name=\"$app\"}[$__rate_interval])) \n)\n/\n(\n    sum(irate(microsoft_aspnetcore_hosting_total_requests{service_name=\"$app\"}[$__rate_interval])) \n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ASP.NET Core Request Volume",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum(irate(microsoft_aspnetcore_hosting_failed_requests{service_name=\"$app\"}[$__rate_interval]))\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P95 Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(irate(dapr_http_server_latency_sum{app_id=\"$app\"}[$__rate_interval])) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}